version: "3.8"

services:
  postgres:
    image: postgres:16.0
    container_name: postgres-db
    ports:
      - 5434:5434
    environment:
      - POSTGRES_DB=db_tinyurls
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app

  account-service:
    build: .
    container_name: tiny-url-api
    ports:
      - 0
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5434/db_tinyurls
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - app

networks:
  app:
    driver: bridge