server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: "localhost:9092"

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
